<?php
session_start();
if(isset($_SESSION['logstatus'])){
	if($_SESSION['logstatus']=='YES'){
		$_SESSION['username']='';
		$_SESSION['password']='';
		$_SESSION['logstatus']='NO';
	}
	header('location:http://localhost/FoodSite/Home.php');
}
else{
	header('location:http://localhost/FoodSite/Home.php');
}
?>